# GitHub Actions workflow for testing gwArsenicR package
# This workflow tests the package on multiple R versions and operating systems
# to ensure compatibility and reliability across different environments

name: R Package Testing - gwArsenicR

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:  # Skip CI for non-code changes
      - "**.md"
      - "**.txt"
      - "docs/**"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Query R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2  # Enable caching for better performance
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::devtools
            any::remotes
          needs: check

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install package dependencies
        run: |
          # Install package dependencies
          remotes::install_deps(dependencies = TRUE, upgrade = "always")
          
          # Install additional testing dependencies
          install.packages(c("covr", "spelling"))
        shell: Rscript {0}

      - name: Check package build
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
          
      - name: Run comprehensive tests
        run: |
          # Set options for better error reporting
          options(warn = 2, error = traceback)
          
          # Load package and run all tests
          devtools::load_all()
          
          # Run tests with better error capture
          tryCatch({
            cat("Running test-gwArsenic.R specifically...\n")
            if (file.exists("tests/testthat/test-gwArsenic.R")) {
              testthat::test_file("tests/testthat/test-gwArsenic.R", reporter = "summary")
              cat("test-gwArsenic.R completed successfully!\n")
            } else {
              cat("Warning: test-gwArsenic.R not found, trying filter approach...\n")
              devtools::test(filter = "gwArsenic", reporter = "summary")
            }
            
            cat("Running full test suite...\n")
            devtools::test(reporter = "summary")
            
            cat("Testing package installation...\n")
            devtools::install(quiet = FALSE)
            library(gwArsenicR)
            
            # Test main function exists
            stopifnot(exists("perform_sensitivity_analysis"))
            cat("All tests completed successfully!\n")
          }, error = function(e) {
            cat("Test failed with error:\n")
            print(e)
            quit(status = 1)
          })
        shell: Rscript {0}

      - name: Test vignette rendering
        run: |
          # Test that vignettes can be built
          if (file.exists("vignettes/gwArsenicR-vignette.Rmd")) {
            cat("Testing vignette rendering...\n")
            tryCatch({
              rmarkdown::render("vignettes/gwArsenicR-vignette.Rmd", 
                              output_dir = tempdir())
              cat("Vignette rendered successfully!\n")
            }, error = function(e) {
              cat("Vignette rendering failed:\n")
              print(e)
              quit(status = 1)
            })
          }
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4  # Updated from v3
        with:
          name: check-results-${{ matrix.config.os }}-r${{ matrix.config.r }}
          path: check

      - name: Show session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

  # Enhanced coverage job with quality gates
  coverage:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only on main branch
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::covr
            any::testthat
            any::devtools
            any::DT
            any::htmltools
          needs: coverage

      - name: Test coverage
        run: |
          # Load package first to make its functions available
          devtools::load_all(".", quiet = FALSE)
          
          # Use package_coverage to ensure the full testthat environment,
          # including helper files, is loaded correctly.
          cat("Generating coverage for the entire package...\n")
          full_cov <- covr::package_coverage(
            type = "tests",
            path = ".",
            clean = TRUE
          )
          
          # Print overall coverage for debugging purposes
          cat("\n=== Overall Package Coverage ===\n")
          print(full_cov)
          
          # Now, filter the full coverage report to isolate gwArsenic.R
          cat("\nFiltering for gwArsenic.R specifically...\n")

          # Print filenames using index in a loop for better debugging
          cat("Available files in coverage report:\n")
          for (i in seq_along(full_cov)) {
            file_info <- full_cov[[i]]
            print('File index:', i, 'Filename:', file_info)
          }
          
          # Find the index of the coverage entry for R/gwArsenic.R
          gwarsenic_index <- 2

          if (length(gwarsenic_index) == 0) {
            cat("❌ ERROR: R/gwArsenic.R not found in coverage results.\n")
            cat("Available files in coverage report:\n")
            all_files <- unique(sapply(full_cov, function(x) x$filename))
            print(all_files)
            quit(status = 1)
          }

          # Directly assign the coverage object for R/gwArsenic.R
          gwarsenic_cov_list <- full_cov[gwarsenic_index]
          
          # Re-create a valid coverage object from the filtered list.
          cov <- gwarsenic_cov_list
          class(cov) <- class(full_cov)
          attr(cov, "package") <- attr(full_cov, "package")
          attr(cov, "relative") <- attr(full_cov, "relative")
          
          cat("Successfully filtered coverage for gwArsenic.R\n")
          
          # Calculate and print coverage percentage
          coverage_pct <- covr::percent_coverage(cov)
          cat(sprintf("\n📊 gwArsenic.R Coverage: %.1f%%\n", coverage_pct))
          
          # Show detailed line-by-line coverage
          cat("\n=== gwArsenic.R Coverage Details ===\n")
          uncovered_lines <- covr::zero_coverage(cov)
          if (length(uncovered_lines) > 0) {
            cat(sprintf("⚠️ %d Uncovered lines in gwArsenic.R:\n", length(uncovered_lines)))
            # Display a sample of uncovered lines
            sample_size <- min(10, length(uncovered_lines))
            for (i in 1:sample_size) {
              line_info <- uncovered_lines[[i]]
              cat(sprintf("  Line %d: %s\n", line_info$line, trimws(line_info$value)))
            }
            if (length(uncovered_lines) > sample_size) {
              cat(sprintf("  ... and %d more\n", length(uncovered_lines) - sample_size))
            }
          } else {
            cat("✅ All lines in gwArsenic.R are covered!\n")
          }
          
          # Generate HTML report for gwArsenic.R only
          cat("\n=== Generating gwArsenic.R Coverage Report ===\n")
          covr::report(cov, file = "gwArsenic-coverage.html")
          
          # Create a focused summary file
          coverage_summary <- data.frame(
            File = "gwArsenic.R",
            Coverage = sprintf("%.1f%%", coverage_pct),
            Status = if(coverage_pct >= 85) "✅ EXCELLENT" else if(coverage_pct >= 75) "✅ GOOD" else if(coverage_pct >= 65) "⚠️ NEEDS IMPROVEMENT" else "❌ INSUFFICIENT",
            Target = "≥85%",
            Uncovered_Lines = length(uncovered_lines),
            stringsAsFactors = FALSE
          )
          cat("\n=== gwArsenic.R Coverage Summary ===\n")
          print(coverage_summary)
          write.csv(coverage_summary, "gwArsenic-coverage-summary.csv", row.names = FALSE)
          
          # Set quality gates
          cat("\n=== Quality Gate Assessment ===\n")
          if (coverage_pct < 65) {
            cat(sprintf("❌ FAIL: gwArsenic.R coverage %.1f%% is below minimum threshold (65%%)\n", coverage_pct))
            quit(status = 1)
          } else if (coverage_pct < 75) {
            cat(sprintf("⚠️ WARNING: gwArsenic.R coverage %.1f%% is below recommended threshold (75%%)\n", coverage_pct))
          } else {
            cat(sprintf("✅ SUCCESS: gwArsenic.R coverage %.1f%% meets quality standards\n", coverage_pct))
          }
          
          # Upload to codecov
          if (Sys.getenv("CODECOV_TOKEN") != "") {
            cat("\nUploading gwArsenic.R coverage to codecov...\n")
            covr::codecov(coverage = cov, flags = "gwArsenic")
          }
        shell: Rscript {0}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4  # Updated from v3
        with:
          name: gwArsenic-coverage-reports
          path: |
            gwArsenic-coverage.html
            gwArsenic-coverage-summary.csv

  # Enhanced documentation validation
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::roxygen2
            any::devtools
            any::pkgdown

      - name: Check documentation
        run: |
          # Set git config for potential commits
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Check that documentation is up to date
          cat("Generating documentation...\n")
          devtools::document()
          
          # Verify no uncommitted changes to documentation
          status_output <- system("git status --porcelain", intern = TRUE)
          if (length(status_output) > 0) {
            cat("Documentation is out of date. Please run devtools::document()\n")
            cat("Changed files:\n")
            system("git status")
            system("git diff")
            quit(status = 1)
          }
          
          cat("Documentation is up to date!\n")
        shell: Rscript {0}

  # pkgdown site generation
  pkgdown:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [test, docs]
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
  
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: any::pkgdown
          needs: website
  
      - name: Build pkgdown site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}
  
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4  # Updated from v2